import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { tmdb } from "@/api/tmdb";

const genres: Record<string, { name: string; id: number }> = { action: { name: "Action", id: 28 }, adventure: { name: "Adventure", id: 12 }, animation: { name: "Animation", id: 16 }, comedy: { name: "Comedy", id: 35 }, crime: { name: "Crime", id: 80 }, drama: { name: "Drama", id: 18 }, horror: { name: "Horror", id: 27 }, romance: { name: "Romance", id: 10749 }, thriller: { name: "Thriller", id: 53 }, "science-fiction": { name: "Science Fiction", id: 878 } };
export function generateStaticParams() { return Object.keys(genres).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const genre = genres[slug]; return { title: genre ? `Film ${genre.name} Terbaik` : "Genre Film", description: genre ? `Daftar film ${genre.name.toLowerCase()} terbaik dan terbaru di Filmanesia.` : "Jelajahi film berdasarkan genre.", alternates: { canonical: `/genre/${slug}` } }; }
export default async function GenrePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const genre = genres[slug]; if (!genre) notFound(); const data = await tmdb.discover.movie({ with_genres: String(genre.id), page: 1 }).catch(() => null); return <article className="mx-auto max-w-5xl space-y-8"><header><h1 className="text-3xl font-bold">Film {genre.name} Terbaik</h1><p className="mt-3 text-muted-foreground">Temukan rekomendasi film {genre.name.toLowerCase()} terbaru, populer, dan rating terbaik.</p></header><section className="grid grid-cols-2 gap-4 sm:grid-cols-4">{data?.results?.slice(0, 20).map((movie) => <Link className="rounded-lg p-2 hover:bg-muted" href={`/movie/${movie.id}`} key={movie.id}><strong>{movie.title}</strong><span className="block text-sm text-muted-foreground">{movie.release_date?.slice(0, 4)}</span></Link>)}</section></article>; }
